### PR TITLE
support loop forever in waveChainTx

### PR DESCRIPTION
**Pull request by urish**
Enables looping forever by passing a `{repeat: true}` element to `waveChainTx()`

### CODE REVIEW

**Comment by guymcswain** [comment]
@urish  Have you tested this on a long repeating waveform, ie > 65536?  How do you stop the waveform in a graceful manner?  I did not implement gpioWaveTxStop() api so I'm wondering if this should be included in your PR.

**Comment by urish** [comment]
Hello @guymcswain , thanks for looking into my PR. In my case, I always send some kind of waveform, so I stop the waveform by sending a different one. However, I do agree that implementing `gpioWaveTxStop` is useful for the general usecase, so I will add it to my PR

**Comment by urish** [comment]
Method added!

I also tested the implementation by connecting an LED to GPIO4 and running the following test script, which stopped the waveform successfully after 10 seconds:

```javascript
const hostname = 'localhost';

const pigpio = require('./pigpio-client').pigpio({ host: hostname });
const promisify = require('util').promisify;

const ready = new Promise((resolve, reject) => {
  pigpio.once('connected', resolve);
  pigpio.once('error', reject);
  pigpio.on('disconnected', () => {
    setTimeout(() => pigpio.connect({ host: hostname }), 1000);
  });
});

function promisifyAll(obj) {
  for (const key of Object.keys(obj)) {
    if (typeof obj[key] === 'function') {
      obj[key] = promisify(obj[key]).bind(obj);
    }
  }
  return obj;
}

function gpio(pin) {
  return promisifyAll(pigpio.gpio(pin));
}

ready.then(async () => {
  console.log('ready');
  const led = gpio(4);
  await led.waveClear();
  await led.waveAddPulse([[1, 0, 100000], [0, 1, 100000]]);
  const blinkWave = await led.waveCreate();
  await led.waveChainTx([{loop: true}, {waves: [blinkWave]}, {repeat: true}]);
  setTimeout(() => led.waveTxStop(), 10000);
}).catch(console.error);
```

**Comment by guymcswain** [comment]
@urish  Nicely done.  Thanks for the contribution.

**Comment by urish** [comment]
Thanks @guymcswain!

Would you be open to adding promise support to this library? I created a prototype in the following branch:

https://github.com/urish/pigpio-client/tree/promises

It maintains backward comparability as it still supports the callback parameter, but now all methods also return a promise. If you are interested, I can create a PR for it.

**Comment by guymcswain** [comment]
Yes, adding promise support had been on my 'to do eventually' list but I never really worked through the implementation.  Your approach is quite elegant!

Allow me some time to test your code branch with my existing applications.  I assume those apps that don't use async/await should run 'as is'.  But those that are written with a promisify wrapper would need to remove the wrapper.  Is that correct?

**Comment by urish** [comment]
I just checked it [the above script](https://github.com/guymcswain/pigpio-client/pull/11#issuecomment-535363910), which uses also `util.promisify`, and it still works after the change, so I guess users of promisify can keep the wrapper. I will open a PR from the new branch, so can we move the discussion over there

**Pull request merged**
